### ISSUE TITLE
Remove the duplicate npm version badge from readme

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#106]
**Describe the bug**

**To Reproduce**
1.
1.
1.

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
Any information about your environment you believe is relevant e.g. node version

**Additional context**

**Comment by shivanshi-s** [comment]
Hey, I am a GraceHopperOSD participant, please assign this to me?
