### ISSUE TITLE
Add semantic-release for automated version management and package publishing

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#107]
Add this: https://github.com/semantic-release/semantic-release

**Comment by rbrishabh** [comment]
I can help!

**Comment by rbrishabh** [comment]
Hmm! I can't seem to run `yarn` on this project. It fails with this:
```
An unexpected error occurred: "https://registry.npmjs.intuit.com:443/artifactory/api/npm/npm-intuit/@babel/helper-compilation-targets/-/helper-compilation-targets-7.10.4.tgz: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/rbrishabh/Desktop/open-source/user-data-for-fraud-prevention/yarn-error.log".
```
Any ideas?

**Comment by reubenae** [comment]
Sorry, it looks like dependabot has messed something up here. Try deleting the yarn lock file and re-running yarn.

**Comment by reubenae** [comment]
@rbrishabh FYI I have fixed that issue in master now - https://github.com/intuit/user-data-for-fraud-prevention/pull/112 

You will need to make sure you're on the latest version of code, but you should be able to run `yarn` in this project now without any issues.

**Comment by ShreyaPrasad1209** [comment]
@reubenae could you elaborate on how you want semantic-release to be added? I'm sorry I'm new to this project so forgive me if my questions sounds naive 😅
