### ISSUE TITLE
Update contributors on readme to reflect all contributors we have for this repo

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#108]
Please check the list of contributors here: https://github.com/intuit/user-data-for-fraud-prevention/graphs/contributors

And update the contributors on readme by following the instructions in the "How contributors get added to the README" section in the readme file.

**Comment by Amishakumari544** [comment]
I would like to take this  @skodamarthi

**Comment by Ayushisood** [comment]
Hii @skodamarthi  I would liike to work in this issue, kindly assign this issue to me under OSD'21

**Comment by reubenae** [comment]
@Ayushisood just go ahead and submit a PR, no need to have an issue assigned. We'll review and merge once its created.
