### ISSUE TITLE
Configure circle CI to publish canary versions on PR's

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#11]
If a PR build passes, it should publish to npm as a canary version, so the developer can test it out in their own repo without having to use yarn link.

https://circleci.com/orbs/registry/orb/auto/release#commands-canary

**Comment by setezad** [comment]
Can I please work on this?

**Comment by reubenae** [comment]
Yep! Submit a PR, but this issue is open for all to submit a PR too.
