### ISSUE TITLE
Remove "auto" related dependencies 

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#110]
We tried adding "auto" to auto-generate releases, but it didn't work as expected. We reverted the changes done to circleCI config file as part of https://github.com/intuit/user-data-for-fraud-prevention/pull/74 for this. However, the changes done in package.json were not reverted. Please remove all "auto" related code in package.json as we are not using this.

**Comment by vvijayalakshmi21** [comment]
Hi,
Can I go ahead and remove everything with term "auto"?
