### ISSUE TITLE
Update readme in hmrc folder to include documenation for "Gov-Client-Local-IPs-Timestamp" header

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#111]
https://github.com/intuit/user-data-for-fraud-prevention/tree/master/src/js/hmrc

Update readme to add details for a new header we added recently.

Gov-Client-Local-IPs-Timestamp - A timestamp to show when Gov-Client-Local-IPs header value is collected.

**Comment by Swastyy** [comment]
Hey, @skodamarthi Can I work on this?

**Comment by skodamarthi** [comment]
@Swastyy Sure...This is open for anyone to contribute. Please submit a PR when you can and we are happy to help if you have any questions.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi 
I presume this can be closed?
