### ISSUE TITLE
Update "Steps for testing" section in readme

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#118]
Remove the demo label, create a new section "How to test" and move the "Steps for testing" section to a new file (DEMO.md)  similar to how it is done for the Usage section https://github.com/intuit/user-data-for-fraud-prevention/blob/master/USAGE.md

**Comment by vvijayalakshmi21** [comment]
What goes in to "How to test" section?

**Comment by vvijayalakshmi21** [comment]
PR #116 has the required changes for this issue as well
Please review and let me know
