### ISSUE TITLE
Add Gov-Client-Browser-JS-User-Agent header to HMRC headers

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#124]
**Is your feature request related to a problem? Please describe.**

Refer to HMRC documentation here to know the info we need to send as part of this header: https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/#gov-client-browser-js-user-agent

**Describe the solution you'd like**
Add a function to fetch useragent using navigator.userAgent and use that function to generate Gov-Client-Browser-JS-User-Agent header needed by HMRC for fraud prevention.

**Describe alternatives you've considered**

**Additional context**

**Comment by rachanamamillapalli** [comment]
@skodamarthi is this issue open for hacktoberfest?

**Comment by reubenae** [comment]
@rachanamamillapalli yes, go ahead. GHC OSD is now over so feel free to pick up any of the issues and submit a PR.

**Comment by rachanamamillapalli** [comment]
Thanks @reubenae. The PR is open but we might have to add the hacktoberfest label to count it

**Comment by skodamarthi** [comment]
@rachanamamillapalli Done! Thank you for the contribution :)
