### ISSUE TITLE
Add Gov-Client-Public-IP header to HMRC headers

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#125]
**Is your feature request related to a problem? Please describe.**
Refer to HMRC documentation here to know the info we need to send as part of this header: https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/#gov-client-public-ip

Describe the solution you'd like
Add a function to fetch public IP address using https://api.ipify.org and use that function to generate Gov-Client-Public-IP header needed by HMRC for fraud prevention.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rachanamamillapalli** [comment]
I would like to work on this! @skodamarthi could you assign this to me?
Will reach out for more details once I explore the repo

**Comment by skodamarthi** [comment]
Hi @rachanamamillapalli, Thank you for your interest in this issue. This is currently reserved for today for the participants of GraceHopper OSD. Feel free to check it later tomorrow and submit a PR if you don't see any comments/contributions by then.

**Comment by rachanamamillapalli** [comment]
@skodamarthi is this issue open for hacktoberfest?

**Comment by bolu-tife** [comment]
Hi @skomarthi 
Can this issue be assigned to me?

**Comment by reubenae** [comment]
@bolu-tife we don't allow people to "claim" issues. You may submit a PR but you may not "sit" on an issue. However, I don't think anyone else is working on this right now.

**Comment by bolu-tife** [comment]
Thank you @reubenae
