### ISSUE TITLE
Configure allcontributors bot

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#13]
https://allcontributors.org/docs/en/bot/installation

**Comment by christyjacob4** [comment]
Hi @reubenae wont this require us to have access to the repo settings?

**Comment by reubenae** [comment]
@christyjacob4 yep, probably. Though if there are other ways to solve this problem we'd welcome a contribution. I didn't label this one deliberately as I think it will be open the repo maintainers have to action.

We would welcome help though (we've never set it up before). If you have that experience and would like to jump on a zoom call and work together with us we would greatly appreciate that (and we can give you credit for solving the issue)

**Comment by christyjacob4** [comment]
I would love that. I haven't set it up myself but I was intending to learn through this issue

**Comment by skodamarthi** [comment]
Can we use auto for this?

An all-contributors plugin exists for it that would automatically add new contributors to the README of the project.

Need to do the following after adding Auto as part of https://github.com/intuit/user-data-for-fraud-prevention/issues/24

- Setup all-contributors

- Add the auto-all-contributors plugin

**Comment by christyjacob4** [comment]
Okay let me get auto setup first and then I can take a look at the all contributors plugin

**Comment by rachelquan** [comment]
Hi! I'm a GHC OSD participant, and I want to try this out! I submitted the form for this issue via Open Track Issue Tracker form!

**Comment by reubenae** [comment]
Thanks for your work @rachelquan !

**Comment by rachelquan** [comment]
> Thanks for your work @rachelquan !

You're welcome! Thank YOU so much for the help & feedback, and for making my first contribution to an open-source project a positive one! 😊
