### ISSUE TITLE
Export screen details header for HMRC (Gov-Client-Screens)

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#138]
**Is your feature request related to a problem? Please describe.**
Currently, we are constructing all the HMRC headers as part of getFraudPreventionHeaders function in https://github.com/intuit/user-data-for-fraud-prevention/blob/master/src/js/hmrc/mtdFraudPrevention.js.

We want to provide the flexibility for users to choose the headers they want from this library independently, instead of providing all of them as a bunch. 

**Describe the solution you'd like**
We want an exported function for Gov-Client-Screens header. Add the functionality to call getScreenData function and construct Gov-Client-Screens header value in the format required by HMRC.

**Comment by RiyaJohn** [comment]
@skodamarthi Added function to support this, let me know if this is how you thought around it
