### ISSUE TITLE
Export local IPs collection timestamp details header for HMRC (Gov-Client-Local-IPs-Timestamp)

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#144]
Is your feature request related to a problem? Please describe.
Currently, we are constructing all the HMRC headers as part of getFraudPreventionHeaders function in https://github.com/intuit/user-data-for-fraud-prevention/blob/master/src/js/hmrc/mtdFraudPrevention.js.

We want to provide the flexibility for users to choose the headers they want from this library independently, instead of providing all of them as a bunch.

Describe the solution you'd like
We want an exported function for Gov-Client-Local-IPs-Timestamp header. Add the functionality to fetch timestamp details for local IP address collection and construct Gov-Client-Local-IPs-Timestamp header value in the format required by HMRC.

**Comment by aditya-rastogi23** [comment]
Ok I'll work on this, could you assign it to me?

**Comment by skodamarthi** [comment]
We do not assign issues to anyone. Please go ahead and submit a PR once it is ready. Let us know if there are any questions.

**Comment by aditya-rastogi23** [comment]
Have created a PR, hopefully this covers what was needed?

**Comment by reubenae** [comment]
Closed with https://github.com/intuit/user-data-for-fraud-prevention/pull/146
