### ISSUE TITLE
Remove moment.js as a dependency

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#15]
Started this work here https://github.com/intuit/user-data-for-fraud-prevention/pull/6 as an example

We use a single function from moment's massive library. The benefit here is to reduce the bundle size; ideally by removing any dependency on moment.js

**Comment by honsq90** [comment]
I can give this a go

**Comment by honsq90** [comment]
seems like yarn.lock is expecting this as the registry url? https://registry.npmjs.intuit.com:443

this preventing me from installing/removing packages. not sure if I want to remove moment.js and update the yarn lockfile.

**Comment by reubenae** [comment]
Thanks @honsq90 - we'll look into that issue. While you are very welcome to contribute a fix for this issue, there is already a PR which has gone through a few iterations open for this issue - https://github.com/intuit/user-data-for-fraud-prevention/pull/6 - you would probably be better off working on another issue so we're not duplicating effort. Would appreciate your review on that PR though, to see if you would have approached this issue differently. Thanks!
