### ISSUE TITLE
Excess downloads when using npm or yarn

### ISSUE THREAD

**Issue by DBrown2207** [intuit/user-data-for-fraud-prevention#150]
**Describe the bug**
When downloading the distributed package from npm repository using npm or yarn, many babel dependencies are downloaded as well. This slows down installation and also adds a lot of files which aren't needed to use the library.
A second issue is the src files are only partially downloaded, so if a user wants to read the source, or directly use the src to reduce bundling uuid dependency twice for example, it throws an error as required files are not found.

**To Reproduce**
1. run `yarn add user-data-for-fraud-prevention`

**Expected behavior**
Only the required node modules are downloaded
Either all or no source files are downloaded

**Screenshots**
Package json:
![image](https://user-images.githubusercontent.com/12028563/137505490-04abb1c0-55a8-41ff-9e4a-3f306942d69c.png)

Downloaded node modules:
![image](https://user-images.githubusercontent.com/12028563/137505437-c4a8a06c-ae7e-4ee9-ba08-9dadc0c5636f.png)

None of these are required except for `user-data-for-fraud-prevention` as the distributed code has been completely bundled by webpack. uuid may make sense if the src files are intended to be used.

**Info (please complete the following information):**
Any information about your environment you believe is relevant e.g. node version

**Additional context**

**Comment by reubenae** [comment]
Fixed, thank you for raising and resolving!
