### ISSUE TITLE
Yeoman generator for new feature

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#16]
**Is your feature request related to a problem? Please describe.**
As a engineer trying to add a new implementation for my problem space, I'd like a generator to automatically scaffold out the files for me

**Describe the solution you'd like**
Say california state taxes require similar information to HMRC about the user's device. You want to leverage the work in js/common, but you need to format it differently to how HMRC want it.

Essentially you need to clone the HMRC folder https://github.com/intuit/user-data-for-fraud-prevention/tree/master/src/js/hmrc but with your own name and then rewrite the functions.

It would be good to have a yeoman generator script you can call which automatically scaffolds this all out.

https://yeoman.io/learning/index.html

**Describe alternatives you've considered**
A good MVP would be a README section for this specific problem more clearly detailing out the structure required.

**Additional context**

**Comment by jitinmaher** [comment]
@reubenae Raised changes for this here: https://github.com/intuit/user-data-for-fraud-prevention/pull/72
