### ISSUE TITLE
Add section to README for expected project structure to make it easier to contribute new implementations

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#17]
MVP of https://github.com/intuit/user-data-for-fraud-prevention/issues/16

The vision for this repo is to have common functionality (in the common folder) but then multiple implementations tweaking the formatting etc for that specific problem space, e.g. HMRC in UK, California state taxes, Ireland personal taxes and so on.

This structure should be detailed in the readme or its own file and linked from the readme.

**Comment by rujuj** [comment]
I'm a Grace Hopper OSD participant and I'd love to take this one :)

**Comment by rujuj** [comment]
@reubenae can I get some clarification on what changes need to be made and where?

**Comment by yashasvimisra2798** [comment]
I did love to contribute to this as a part of Grace Hopper OSD 2021, can you please elaborate more on what exactly needs to be done?

**Comment by yashasvimisra2798** [comment]
Can I please get some inputs on what needs to be done?

**Comment by reubenae** [comment]
Sure. So currently all implementation specific to HMRC (the tax agency in the UK) is within the `hmrc` folder https://github.com/intuit/user-data-for-fraud-prevention/tree/master/src/js

We expect the repo to maintain this structure, where common/non-specific code is within the common folder, and then implementation specific is within a specific folder.

The idea here is that two implementations may collect the same data, but require it in a different format. Hence this separation. It will also allow us to easily expand the code owners in the future.
 
This issue is just to document some of that in the readme to help out people coming to this repo for the first time.

**Comment by yashasvimisra2798** [comment]
Ok @reubenae , I'll work on this
