### ISSUE TITLE
Add renovate for automated dependency updates

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#26]
https://www.npmjs.com/package/renovate

**Comment by honsq90** [comment]
I can give this a go as well

**Comment by fandok** [comment]
hi, if you want to applied this, i think the participant should have access to install things in your repo based on this https://github.com/renovatebot/renovate i can maybe do this, but i must have the access to your repo to install certain things

**Comment by skodamarthi** [comment]
@fandok Thanks for your comment! It would probably be easier if I or @reubenae work on this. We will get back to you incase we need help on this.

**Comment by reubenae** [comment]
We have dependabot taking care of this now - should we update this issue or create a new issue to remove the unused renovate config?

**Comment by reubenae** [comment]
Ah, dependabot only handles vulnerabilities. We still need to add the renovate bot to this project, but as you need to be an admin to do that I think we can close this issue until one of us handles it
