### ISSUE TITLE
Improve Contributing section of ReadMe 

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#30]
Point 6 of Contributing section in ReadMe can be improved by adding links for documentation directly under `yarn link` and `npm link`directly. 

Also it would be good to add an additional point there with a link to our demo project:

Test your changes in your consuming code or using our demo project by running yarn link or npm link.

**Comment by reubenae** [comment]
We already have a demo section in the README https://github.com/intuit/user-data-for-fraud-prevention#demo

One addition to this though would be that people can't "claim" issues as their own. If you want to contribute, just add a PR, you don't need to let us know in advance.
