### ISSUE TITLE
Code clean up: Remove the unnecessary return while using arrow functions

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#32]
Eg: https://github.com/intuit/user-data-for-fraud-prevention/blob/master/src/js/common/globalsUtil.js

**Comment by jakubkoje** [comment]
I'm gonna look at it.

**Comment by khanna98** [comment]
Solved this issue in this pull request: https://github.com/intuit/user-data-for-fraud-prevention/pull/33
