### ISSUE TITLE
Add jsDocs for exported functions

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#36]
Please add jsDocs to document all the exported functions that are missing docs.

**Comment by reubenae** [comment]
I really don't like this idea. For exported functions that are used by consumers, sure, but not internal ones.
Typescript migration is a much better way to ensure functions are called correctly as behave as expected. JS doc just clutters up files IMO.

**Comment by jitinmaher** [comment]
@skodamarthi @reubenae Added a PR for the same [here](https://github.com/intuit/user-data-for-fraud-prevention/pull/62).
