### ISSUE TITLE
Add code to generate UUID for one of the HMRC headers 

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#41]
Enhance this library to generate value for a new HMRC header: Gov-Client-Device-ID

You can generate an universally unique identifier (UUID), also known as a globally unique identifier (GUID), to use as a device ID

HMRC's documentation for this header can be found here: https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/

Expected format:
Gov-Client-Device-ID: beec798b-b366-47fa-b1f8-92cede14a1ce

**Comment by salilbc** [comment]
@skodamarthi Can i take this up?

**Comment by skodamarthi** [comment]
Hi @salilbc.. Sure :) But please note that another participant at @gracehopperOSD is also working on this. If there are multiple PRs raised, we will take a look at all of them and merge the one that is most suitable. Please let me know if you have any questions. Thanks!

**Comment by salilbc** [comment]
so just to confirm, I need to add a new header Gov-Client-Device-ID( in UUID format) to the to mtdFraudPrevention.js and update the unit tests?

**Comment by skodamarthi** [comment]
@salilbc Yes..that's right! Follow the same pattern as the other headers in mtdFraudPrevention.js. The expected format for this header is: Gov-Client-Device-ID: beec798b-b366-47fa-b1f8-92cede14a1ce

**Comment by salilbc** [comment]
PR is raised for this issue with all review comments resolved. please merge if this looks fine
 https://github.com/intuit/user-data-for-fraud-prevention/pull/54
