### ISSUE TITLE
Update demo section in readme with steps for testing

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#60]
Here are the steps to test:

- Run yarn link in user-data-for-fraud-prevention
- Clone the demo project, in there:

> - Run yarn
> - Run yarn start
> - Run yarn demo
> - Run yarn link "user-data-for-fraud-prevention"

Now you can make changes in user-data-for-fraud-prevention locally and they will instantly reflect in the demo project.

You can check the browser console for errors.

**Comment by salilbc** [comment]
I can take this up

**Comment by K-Kumar-01** [comment]
I would also like to have a go on this
