### ISSUE TITLE
Linting tasks should run as part of circle CI - and fail the build if there are issues.

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#66]
It would be good to have the linting a separate step so it reports separately to the tests on the PR.

**Comment by vivek32ta** [comment]
Hi @reubenae I'd like to take this up

**Comment by camsvn** [comment]
Is this issue taken?

**Comment by skodamarthi** [comment]
Hi @camsvn.. @vivek32ta is working on this at the moment. Feel free to take a look at the open PR and create another one if you have a different approach.

**Comment by vivek32ta** [comment]
Hi @skodamarthi... I'm waiting for the reviewers to review the PR. 

Thanks :)

**Comment by skodamarthi** [comment]
Thanks @vivek32ta I reviewed the PR and left some comments. Please take a look when you can.
