### ISSUE TITLE
Create README.md for HMRC Fraud headers

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#8]
At the moment, information on how to use the HMRC fraud headers functions are contained within the project's main README. It would be best to have a seperate one and link to it from the main.

**Comment by interactwithankush** [comment]
I would like to contribute. Can I please be assigned to this problem?

**Comment by reubenae** [comment]
Hi @interactwithankush - we do not assign issues in this repo. It makes organising too difficult. If you wish to contribute just open a PR for it and we will review. Please feel free to ask any questions you have on this issue first :)
