### ISSUE TITLE
Export screen and window details for HMRC integrations

### ISSUE THREAD

**Issue by JohanAludden** [intuit/user-data-for-fraud-prevention#87]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to send the details of the screen and window as separate headers, at the moment we get a single screen and window value from the headers.

**Describe the solution you'd like**
I want to have the possibility to get screen width, hight, color depth and scaling as well as the window width and height.

**Describe alternatives you've considered**
Splitting the value supplied in the SCREEN and WINDOW headers.

**Additional context**

**Comment by reubenae** [comment]
Thanks for the contribution, @JohanAludden !
